services:
# Microservice Configuration    
    userservice:
        build: ./UserServiceGrpc
        container_name: UserServiceContainer
        ports:
            - "5001:5001"
    productservice:
        build: ./ProductServiceGrpc
        container_name: ProductServiceContainer
        ports:
            - "5002:5002"
    orderservice:
        build: ./OrderServiceGrpc
        container_name: OrderServiceContainer
        ports:
            - "5004:5004"
    apigateway:
        build: ./API Gateway
        container_name: APIGatewayContainer
        ports:
            - "5003:5003"
        depends_on:
            - userservice
            - productservice
            - orderservice  

#Network Configuration
networks:
    default:
        name: ecom_services
    